CREATE TABLE burgers (
	id INTEGER AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(100) NOT NULL,
	eaten BOOLEAN NOT NULL,
	date TIMESTAMP NOT NULL,
	PRIMARY KEY(id)
);

ALTER TABLE burgers MODIFY date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL;

SELECT * FROM burgers;